theme: jekyll-theme-cayman
title: Disaster Accountability Project -- Miscellaneous Web Pages
description: This website hosts various web pages used by DAP team members.
For example, the translation tool enables DAP developers to scrub translation files by comparing them to the base-format translation file, en.json.
