theme: jekyll-theme-cayman
title: Disaster Accountability Project Miscellaneous Web Pages
description: The translation tool enables DAP developers to scrub translation files by comparing them to the base-format translation file, en.json.
